### ISSUE TITLE
Support for elm Array

### ISSUE THREAD

**Issue by rl-king** [folq/haskell-to-elm#11]
I'm guessing mapping [Vector](https://hackage.haskell.org/package/vector-0.12.1.2/docs/Data-Vector.html) to elm [Arrays](https://package.elm-lang.org/packages/elm/core/latest/Array) would make the most sense?

Both [encoder](https://package.elm-lang.org/packages/elm/json/latest/Json-Encode#array) and [decoders](https://package.elm-lang.org/packages/elm/json/latest/Json-Decode#array) are available in elm/json.

**Comment by ollef** [comment]
Sounds great!

Would you like to contribute this feature?

**Comment by rl-king** [comment]
👍 I'll give it a go

**Comment by ollef** [comment]
Cheers!
