### ISSUE TITLE
Support more Haskell number types

### ISSUE THREAD

**Issue by rl-king** [folq/haskell-to-elm#12]
Since Elm has only two number types everything would map to an Int or Float. Which are also limited to what JS can represent. 

Any reason more types aren't supported already? Or just no need for it yet?

**Comment by ollef** [comment]
Which ones are you thinking of? We haven't needed any more yet, but I think it seems good to support anything that's reasonably close to the Elm types.

So `Integer` would perhaps be an exception unless there's a de facto standard bigint package for Elm.

**Comment by rl-king** [comment]
As I was working on some stuff with [hasql](https://hackage.haskell.org/package/hasql-1.4.4/docs/Hasql-Encoders.html#v:int4) and [cryptonite](https://hackage.haskell.org/package/cryptonite-0.24/docs/Crypto-OTP.html#t:OTP) I derived instances for Int32 and Word32. 

So `Int8`, `Int16`, `Int32` and `Int64` seem fine since they're all similar to the already present `Int`.

`Word8`,`Word16`, `Word32` and `Word64` could map to Int as well, with Word64 having the same caveat as Int(64), losing some precision at large numbers.

And Haskell `Float` to Elm `Float`

**Comment by rl-king** [comment]
I've never had the need for bigint in Elm so don't know much about packages related to it. I'd say limiting the scope of instances to core is reasonable as well.
