### ISSUE TITLE
Using DerivingVia only for a subset of types

### ISSUE THREAD

**Issue by parry84** [folq/haskell-to-elm#19]
Dear folq guys, in my project I've:
- Many types are derived via `ElmType`
- Just one type (in my case is `Lifetime`) is derived via `deriveElmJSON*` (in order to set a non-default option)

here the source code: https://github.com/parry84/fidelio/blob/69510b6f8b6042f627c642ff810223d3b479e561/Web/JsonTypes.hs

but, when I generate the Elm type I only get the last one:

here the results: https://github.com/parry84/fidelio/blob/69510b6f8b6042f627c642ff810223d3b479e561/elm/Api/Generated.elm

If I derive the last one via the `ElmType` as well, everything works fine (except that I miss my option, of course).
I don't understand if I missed something or the library doesn't allow me to mix the two deriving styles.

I hope you could help me. Thanks in advance (btw, congratulation for your package :-)

**Comment by ollef** [comment]
Hello!

It kind of looks like you're writing all the output modules to the same file, resulting in whatever module is written last becoming your `Generated.elm`, though I couldn't find the code that generates those files to confirm this. Notice that you've written the `Api.Generated.Lifetime` module to where `Api.Generated` should be.

**Comment by parry84** [comment]
Hello ollef, thanks for your hint!

The issue was that, while my `elmDefinition` is `Just $ deriveElmTypeDefinition @Lifetime LHTE.defaultOptions "Api.Generated.Lifetime"`, my `elmEncoderDefinition` should have been `Just $ deriveElmJSONEncoder @Lifetime LHTE.defaultOptions Aeson.defaultOptions "Api.Generated.encoder"`, and not ` "Api.Generated.Litetime.encoder"`!

Thanks again.
