### ISSUE TITLE
Converting Types containing Sets or Maps

### ISSUE THREAD

**Issue by Maxfield-Chen** [folq/haskell-to-elm#5]
I'm trying to use this wonderful library to convert a data structure containing a set of my custom data type as follows:

`data Group =
  Group
    { _liberties :: S.Set CustomType
    , _members :: S.Set CustomType
    }   deriving (Show, Eq, Generic, ToJSON, SOP.Generic, SOP.HasDatatypeInfo)
`

When writing the instance declarations for HasElmType, I get an error stating that there is no instance for HasElmType (S.Set CustomType).

I tried to define this myself, but found that these instances rely on SOP.Generic and Generic instances which I could not derive for a Set or a Map (using StandaloneDerivations) as all the required constructors are not exported. 

This isn't a bug report, just a humble request for guidance. Is there a way to convert the above custom data type to elm code? I love the idea of this library and have it working for my other types, awesome work!

**Comment by Maxfield-Chen** [comment]
And I just saw the pull request. Closing this, sorry!

**Comment by ollef** [comment]
No problem! If you were able to find a solution that you liked, would you like to contribute it to the readme?
