### ISSUE TITLE
Document usage with deriving via

### ISSUE THREAD

**Issue by ollef** [folq/haskell-to-elm#6]
This can cut down on the boilerplate a lot.

**Comment by domenkozar** [comment]
Could this ship as part of haskell-to-elm or does it need to be copy/paste?

**Comment by ollef** [comment]
The reason it's not included is that it doesn't allow you to specify the Aeson and haskell-to-elm options. If it's of any use, perhaps we could include version with just the default options?

**Comment by domenkozar** [comment]
If someone wants that they'll have to copy either way :)
