### ISSUE TITLE
Export lists

### ISSUE THREAD

**Issue by georgefst** [folq/haskell-to-elm#8]
Minor thing, but is it currently possible to use explicit export lists in the generated code?

I'd quite like to compile without warnings for various reasons, and this is the one thing currently preventing me from doing so (unless I do the work myself, but hey, this package is meant for us lazy people...).

**Comment by ollef** [comment]
It's not currently possible to do this.

What's producing the warning? elm-analyse? We turn that warning off with `checks: { "ExposeAll": false }` in our `elm-analyse.json`, as we don't find it to be of any value. You could also exclude the generated code from being analysed with `excludePaths`.

I would accept a PR that adds explicit export lists if you still want it. It shouldn't be too much trouble to do.

**Comment by georgefst** [comment]
Yeah, it's coming from `elm-analyse`. Those seem like two very reasonable suggestions, thanks (I'm very new to Elm, so I haven't quite found my way around all the tooling yet).

I'll look into implementing it anyway.

**Comment by ollef** [comment]
Cool! Here's where you need to look: https://github.com/folq/elm-syntax/blob/0bed7db2095fa7c3c9367e94effe93e4bf62f54e/src/Language/Elm/Pretty.hs#L96
